// This is an autogenerated file from Firebase Studio.
'use server';
/**
 * @fileOverview Provides AI-powered health assistance.
 *
 * - aiHealthAssistant - A function that handles health-related questions.
 * - AiHealthAssistantInput - The input type for the aiHealthAssistant function.
 * - AiHealthAssistantOutput - The return type for the aiHealthAssistant function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const AiHealthAssistantInputSchema = z.object({
  query: z.string().describe('The health-related question from the user.'),
});
export type AiHealthAssistantInput = z.infer<typeof AiHealthAssistantInputSchema>;

const AiHealthAssistantOutputSchema = z.object({
  answer: z.string().describe('The summarized and easy-to-understand answer to the user question.'),
});
export type AiHealthAssistantOutput = z.infer<typeof AiHealthAssistantOutputSchema>;

export async function aiHealthAssistant(input: AiHealthAssistantInput): Promise<AiHealthAssistantOutput> {
  return aiHealthAssistantFlow(input);
}

const aiHealthAssistantPrompt = ai.definePrompt({
  name: 'aiHealthAssistantPrompt',
  input: {schema: AiHealthAssistantInputSchema},
  output: {schema: AiHealthAssistantOutputSchema},
  prompt: `You are a helpful AI assistant providing summarized and easy-to-understand answers to health-related questions.

  Question: {{{query}}}
  Answer: `,
});

const aiHealthAssistantFlow = ai.defineFlow(
  {
    name: 'aiHealthAssistantFlow',
    inputSchema: AiHealthAssistantInputSchema,
    outputSchema: AiHealthAssistantOutputSchema,
  },
  async input => {
    const {output} = await aiHealthAssistantPrompt(input);
    return output!;
  }
);
