import type { Product, LabTest } from '@/types';

export const mockProducts: Product[] = [
  {
    id: '1',
    name: 'Paracetamol 500mg',
    description: 'Effective relief from pain and fever. Suitable for adults and children over 12 years.',
    price: 5.99,
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'medicine painkiller',
    category: 'Pain Relief',
    dosage: '1-2 tablets every 4-6 hours',
    usage: 'For mild to moderate pain and fever.',
    sideEffects: 'Rare, but can include allergic reactions.',
    stock: 100,
  },
  {
    id: '2',
    name: 'Vitamin C 1000mg',
    description: 'Boosts immune system and provides antioxidant support.',
    price: 12.50,
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'vitamin supplement',
    category: 'Vitamins & Supplements',
    dosage: '1 tablet daily',
    usage: 'To support immune health.',
    sideEffects: 'Generally well-tolerated.',
    stock: 50,
  },
  {
    id: '3',
    name: 'Amoxicillin 250mg',
    description: 'Antibiotic for treating bacterial infections. Prescription required.',
    price: 8.75,
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'antibiotic pills',
    category: 'Prescription',
    dosage: 'As prescribed by doctor',
    usage: 'For bacterial infections.',
    sideEffects: 'May cause nausea or diarrhea.',
    stock: 30,
  },
  {
    id: '4',
    name: 'Saline Nasal Spray',
    description: 'Gentle relief for nasal congestion and dryness.',
    price: 7.20,
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'nasal spray',
    category: 'Cold & Flu',
    usage: 'For clearing nasal passages.',
    stock: 75,
  },
  {
    id: '5',
    name: 'Ibuprofen 200mg',
    description: 'Reduces inflammation and relieves pain.',
    price: 6.50,
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'painkiller medicine',
    category: 'Pain Relief',
    stock: 120,
  },
  {
    id: '6',
    name: 'Multivitamin Gummies',
    description: 'Daily essential vitamins for adults in a tasty gummy form.',
    price: 15.00,
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'vitamin gummies',
    category: 'Vitamins & Supplements',
    stock: 60,
  }
];

export const mockLabTests: LabTest[] = [
  {
    id: 'lt1',
    name: 'Complete Blood Count (CBC)',
    description: 'Measures different components of your blood, including red and white blood cells, hemoglobin, and platelets.',
    price: 45.00,
    preparation: 'No special preparation needed. You can eat and drink normally.',
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'blood test',
  },
  {
    id: 'lt2',
    name: 'Lipid Panel',
    description: 'Measures fats and fatty substances used as a source of energy by your body. Includes cholesterol and triglycerides.',
    price: 60.00,
    preparation: 'Fasting for 9-12 hours is usually required before this test.',
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'lab analysis',
  },
  {
    id: 'lt3',
    name: 'Thyroid Stimulating Hormone (TSH)',
    description: 'Checks thyroid gland function and helps diagnose thyroid disorders.',
    price: 55.00,
    preparation: 'Inform your doctor about any medications you are taking.',
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'medical test',
  },
  {
    id: 'lt4',
    name: 'Glucose Test (Fasting)',
    description: 'Measures the level of glucose in your blood after an overnight fast. Used to screen for diabetes.',
    price: 30.00,
    preparation: 'Fasting for at least 8 hours is required.',
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'diabetes test',
  }
];
